version: '3'

services:
  webapp:
    build:
      context: ./flask-app
    container_name: webapp
    restart: always
    ports:
      - "5001:5000"
    depends_on:
      - db
    deploy:
      replicas: 3

  proxy:
    build:
      context: ./nginx-proxy
    container_name: proxy
    restart: always
    ports:
      - "80:80"
    depends_on:
      - webapp

  db:
    image: redis:latest
    container_name: db
    restart: always
    ports:
      - "6379:6379"
